In [39]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# scalar

In [40]:

scalar = torch.tensor(7)
scalar

tensor(7)

In [41]:
scalar.ndim

0

In [42]:
scalar.item()

7

# vector

In [43]:

vector = torch.tensor([7, 7])
vector  

tensor([7, 7])

In [44]:
vector.ndim 

1

In [45]:
vector.shape

torch.Size([2])

# MATRIX

In [46]:

MATRIX = torch.tensor([[7, 8],
                     [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [47]:
MATRIX.ndim

2

In [48]:
MATRIX[0]

tensor([7, 8])

In [49]:
MATRIX.shape      

torch.Size([2, 2])

In [50]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [51]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [54]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0314, 0.8884, 0.2154, 0.3620],
        [0.8598, 0.0262, 0.0973, 0.1707],
        [0.2055, 0.9210, 0.5971, 0.7335]])

In [55]:
random_tensor.ndim

2

In [56]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# zeros and ones

In [57]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
ones.dtype

torch.float32

In [61]:
# create a range

one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# create tensor like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatypes


In [63]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [64]:
float_32_tensor.dtype

torch.float32

In [65]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [66]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [67]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [68]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [69]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6393, 0.9339, 0.9763, 0.1960],
        [0.0088, 0.1190, 0.1633, 0.1386],
        [0.6071, 0.3713, 0.3846, 0.5110]])

In [70]:
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6393, 0.9339, 0.9763, 0.1960],
        [0.0088, 0.1190, 0.1633, 0.1386],
        [0.6071, 0.3713, 0.3846, 0.5110]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device tensor is on: cpu


# manipulating tensors

In [71]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [72]:
tensor * 10

tensor([10, 20, 30])

In [73]:
tensor - 10 

tensor([-9, -8, -7])

In [74]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [77]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [78]:
torch.matmul(tensor, tensor)

tensor(14)

# shaper erros

In [80]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

#torch.mm = torch.matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [81]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [84]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [85]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor Aggregation

In [87]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [89]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [90]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [92]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [93]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [97]:
x, x.argmin()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0))

In [98]:
x[0]

tensor(0)

In [99]:
x, x.argmax()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(9))

In [100]:
x[9]

tensor(90)

In [101]:
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [107]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [108]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [110]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [115]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [117]:
x_reshaped, x_reshaped.squeeze()

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [118]:
x_reshaped.size(), x_reshaped.squeeze().size()

(torch.Size([9, 1]), torch.Size([9]))

In [119]:
x_reshaped = x_reshaped.reshape(1, 9)

In [121]:
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)

x_squeezed.shape, x_unsqueezed.shape

(torch.Size([9]), torch.Size([9, 1]))

In [124]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# indexing

In [125]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [126]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [127]:
x[0][0]

tensor([1, 2, 3])

In [128]:
x[:, 0]

tensor([[1, 2, 3]])

In [129]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [130]:
x[0, 0, :]

tensor([1, 2, 3])

In [133]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# reproducibility

In [135]:
import torch 
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9671, 0.6664, 0.0265, 0.4810],
        [0.0254, 0.0873, 0.5410, 0.9026],
        [0.8347, 0.2040, 0.7542, 0.0116]])
tensor([[0.5446, 0.9456, 0.6631, 0.0491],
        [0.6817, 0.7529, 0.4815, 0.1056],
        [0.1843, 0.7700, 0.0393, 0.5823]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [137]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [139]:
import torch
torch.cuda.is_available()

True

In [140]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [141]:
torch.cuda.device_count()

1

In [142]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [143]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [144]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [145]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)